### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by anrom7** [Oleksandra2020/Final_project#1]
Не впевнений що добре все зрозумів. В темі написав своє розуміння.
 
Тема: Пошук відео за субтитрами.

**Comment by Oleksandra2020** [comment]
Пошук швидше відбуватиметься за ключовими словами, які введе користувач, а потім буде знаходитися відео, у субтитрах яких найчастіше з'являються ці слова.

**Comment by Oleksandra2020** [comment]
@anrom7 Добрий вечір, пошук швидше відбуватиметься за ключовими словами, які введе користувач, а потім буде знаходитися відео, у субтитрах яких найчастіше з'являються ці слова.

**Comment by Oleksandra2020** [comment]
Також я планую робити пошук українською та по відео з TED конференцій, бо більшість з них мають українські субтитри. Тому моя пропозиція теми: "Пошук TED конференцій українською мовою".

**Comment by anrom7** [comment]
Добре
